name: Kt Lint Check and Auto-fix

on:
  pull_request:
    branches: [ 'develop', 'uat', 'prod' ]
  push:
    branches: [ 'develop', 'uat', 'prod' ]

jobs:
  kt-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          android: false
          fail_on_error: false
          ktlint_version: 0.50.0
          args: "--format"  # This will auto-format the code

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'style: auto formatting with ktlint'
          title: 'style: ktlint auto-format'
          body: |
            Auto-formatting changes applied by ktlint.
            
            Changes include:
            - Code formatting according to Kotlin style guide
            - Import optimization
            - Other style fixes
            
            Please review the changes carefully.
          branch: style/kt-lint-format
          base: ${{ github.head_ref }}
          delete-branch: true