name: Kt Lint Check and Auto-fix

on:
  pull_request:
    branches: [ 'develop', 'uat', 'prod' ]
  push:
    branches: [ 'develop', 'uat', 'prod' ]

jobs:
  kt-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Add ktlint task to build.gradle.kts
        run: |
          if [ -f build.gradle.kts ]; then
            # Verifica se as configurações do ktlint já existem
            if ! grep -q "id(\"org.jlleitschuh.gradle.ktlint\")" build.gradle.kts; then
              # Adiciona o plugin do ktlint
              sed -i '1i plugins {\n    id("org.jlleitschuh.gradle.ktlint") version "11.6.1"\n}' build.gradle.kts
            fi
          else
            echo "plugins {
                id(\"org.jlleitschuh.gradle.ktlint\") version \"11.6.1\"
            }" > build.gradle.kts
          fi

      - name: Run ktlint format
        run: ./gradlew ktlintFormat

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '- Auto formatting with kt-lint.'
          title: 'STYLE (kt-lint): '
          body: |
            - Auto formatting with kt-lint.
          branch: style/kt-lint-format
          base: ${{ github.head_ref }}
          delete-branch: true